-- 01_plans.seed.sql
-- Contact unlock pricing plans. Mirrors db/data/plans.json exactly.

INSERT INTO plans (id, name, slug, description, tagline, price, currency, unlock_quota, duration_days, billing_cycle, tier, features, highlight, display_order, is_active, created_at)
VALUES
  ('plan-single-001',
   'Starter',
   'single',
   'Unlock 1 property in a month. Expires after 30 days.',
   'Try it out — pay as you go',
   9.00,
   'INR',
   1,
   30,
   'monthly',
   'single',
   '["Unlock 1 property contact in a month", "Expires after 30 days", "No commitment, no auto-renew", "Pay securely via Razorpay"]'::jsonb,
   FALSE,
   1,
   TRUE,
   '2026-01-01T00:00:00.000Z'),
  ('plan-cart-001',
   'Multi-Property Pack',
   'cart',
   'Unlock up to 12 properties in a month. Expires after 30 days.',
   'For active buyers — better value',
   100.00,
   'INR',
   12,
   30,
   'monthly',
   'bundle',
   '["Unlock up to 12 property contacts in a month", "Expires after 30 days", "Add from Wishlist or Search", "Pay securely via Razorpay"]'::jsonb,
   TRUE,
   2,
   TRUE,
   '2026-01-01T00:00:00.000Z'),
  ('plan-premium-001',
   'Premium Monthly',
   'premium',
   'Unlock up to 65 properties in a month — best value for serious buyers and agents.',
   'Best value — lowest per-unit price',
   500.00,
   'INR',
   65,
   30,
   'monthly',
   'pro',
   '["Unlock up to 65 property contacts in a month", "Expires after 30 days", "Priority support", "Pay securely via Razorpay"]'::jsonb,
   FALSE,
   3,
   TRUE,
   '2026-01-01T00:00:00.000Z')
ON CONFLICT (id) DO UPDATE SET
  name           = EXCLUDED.name,
  slug           = EXCLUDED.slug,
  description    = EXCLUDED.description,
  tagline        = EXCLUDED.tagline,
  price          = EXCLUDED.price,
  unlock_quota   = EXCLUDED.unlock_quota,
  duration_days  = EXCLUDED.duration_days,
  billing_cycle  = EXCLUDED.billing_cycle,
  tier           = EXCLUDED.tier,
  features       = EXCLUDED.features,
  highlight      = EXCLUDED.highlight,
  display_order  = EXCLUDED.display_order,
  is_active      = EXCLUDED.is_active,
  created_at     = EXCLUDED.created_at;
